# PCA
steps: transform an 𝑁 × 𝑑 matrix 𝑋 into an 𝑁 × 𝑚 matrix 𝑌  

## Sklearn example: 

In [1]:
>>> import numpy as np
>>> from sklearn.decomposition import PCA
>>> X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
>>> pca = PCA(n_components=2)
>>> pca.fit(X)
PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)
>>> print(pca.explained_variance_ratio_)  
>>> print(pca.singular_values_)  
print '\n' 
print X, '\n', pca.transform(X)


/Users/hm0/anaconda2/lib/python2.7/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array


[ 0.99244289  0.00755711]
[ 6.30061232  0.54980396]


[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]] 
[[ 1.38340578  0.2935787 ]
 [ 2.22189802 -0.25133484]
 [ 3.6053038   0.04224385]
 [-1.38340578 -0.2935787 ]
 [-2.22189802  0.25133484]
 [-3.6053038  -0.04224385]]


## Step-by-step example: 
1. Centralized the data (subtract the mean) 
2. Calculate the 𝑑 × 𝑑 covariance matrix: $ C = \frac{1}{N-1} X^T X $ 
3. Calculate the eigenvectors of the covariance matrix (orthonormal). 
4. Select m eigenvectors that correspond to the largest m eigenvalues to be the new basis. 
5. Project the data

### Step 1: subtract the mean

### Step 2: calculate the covariance matrix C

In [2]:
C = np.matmul(X.T, X)/(len(X)-1.0)

In [3]:
pca.get_covariance()

array([[ 5.6,  3.6],
       [ 3.6,  2.4]])

### Step 3: Calculate the eigenvectors and eigenvalue 

In [4]:
pca.components_

array([[-0.83849224, -0.54491354],
       [ 0.54491354, -0.83849224]])

In [5]:
from numpy import linalg as LA

In [6]:
w, v = LA.eig(np.matmul(X.T, X)/(len(X)-1.0)) 
w, v

(array([ 7.93954312,  0.06045688]), array([[ 0.83849224, -0.54491354],
        [ 0.54491354,  0.83849224]]))

### Step 5: Project the data 
$ 𝑉 = [𝑣_1,... 𝑣_𝑚] $ 

The projected data: $𝑌 = 𝑋 𝑉$ is 𝑁 × 𝑚 matrix.

In [7]:
v

array([[ 0.83849224, -0.54491354],
       [ 0.54491354,  0.83849224]])

In [8]:
Y = np.matmul(X, v)
Y

array([[-1.38340578, -0.2935787 ],
       [-2.22189802,  0.25133484],
       [-3.6053038 , -0.04224385],
       [ 1.38340578,  0.2935787 ],
       [ 2.22189802, -0.25133484],
       [ 3.6053038 ,  0.04224385]])

In [9]:
pca.transform(X)

array([[ 1.38340578,  0.2935787 ],
       [ 2.22189802, -0.25133484],
       [ 3.6053038 ,  0.04224385],
       [-1.38340578, -0.2935787 ],
       [-2.22189802,  0.25133484],
       [-3.6053038 , -0.04224385]])

### Reconstruction

In [10]:
X_re = np.matmul(Y, LA.inv(v)) 
X_re

array([[-1., -1.],
       [-2., -1.],
       [-3., -2.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  2.]])

### Scramable

In [11]:
print C
np.random.shuffle(C)
C

[[ 5.6  3.6]
 [ 3.6  2.4]]


array([[ 3.6,  2.4],
       [ 5.6,  3.6]])

In [12]:
w, v = LA.eig(C) 
w, v

(array([ 7.26606056, -0.06606056]), array([[ 0.54772256, -0.54772256],
        [ 0.83666003,  0.83666003]]))

In [13]:
Y = np.matmul(X, v)
Y

array([[-1.38438258, -0.28893747],
       [-1.93210514,  0.25878509],
       [-3.31648773, -0.03015238],
       [ 1.38438258,  0.28893747],
       [ 1.93210514, -0.25878509],
       [ 3.31648773,  0.03015238]])

In [14]:
X_re = np.matmul(Y, LA.inv(v)) 
X_re

array([[-1., -1.],
       [-2., -1.],
       [-3., -2.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  2.]])

## PCA-iris

In [37]:
import numpy as np
import sklearn.datasets, sklearn.decomposition

X = sklearn.datasets.load_iris().data
mu = np.mean(X, axis=0)

pca = sklearn.decomposition.PCA()
pca.fit(X)

nComp = 2
Xhat = np.dot(pca.transform(X)[:,:nComp], pca.components_[:nComp,:])
Xhat += mu

print(Xhat[0,])

[ 5.08303897  3.51741393  1.40321372  0.21353169]


In [38]:
X[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [39]:
Xhat[0]

array([ 5.08303897,  3.51741393,  1.40321372,  0.21353169])

In [40]:
pca.explained_variance_

array([ 4.22824171,  0.24267075,  0.0782095 ,  0.02383509])

In [41]:
sum((sum((X-Xhat)**2)/len(X)))

0.10136429572959302

In [42]:
pca.explained_variance_ratio_

array([ 0.92461872,  0.05306648,  0.01710261,  0.00521218])